export default {
  CLEAR: 'CLEAR',
  FETCH: 'FETCH_USER',
  SET_BUS: 'SET_BUS',
  FETCH_DRIVER: 'FETCH_DRIVER',
  AUTH_ERROR: 'AUTH_ERROR',
  LOGOUT: 'LOGOUT',

  SET_SNACK_STATE: 'SET_SNACK_STATE',
  CLEAR_SNACK: 'CLEAR_SNACK',

  SET_TRIPS_VISIBLE: 'SET_TRIPS_VISIBLE',
  FETCH_TRIPS: 'FETCH_TRIPS',
  CLEAR_TRIPS: 'CLEAR_TRIPS',
  CLEAR_TRIPS_AND_SET_VISIBLE: 'CLEAR_TRIPS_AND_SET_VISIBLE',
  FETCH_TRIPS_CHECKPOINTS: 'FETCH_TRIPS_CHECKPOINTS',
  NO_TRIPS: 'NO_TRIPS',

  SET_MY_LOCATION: 'SET_MY_LOCATION',
  SET_NEAREST_CHECKPOINT: 'SET_NEAREST_CHECKPOINT',
  SET_TRACKING: 'SET_TRACKING',
  SET_DURATION_DISTANCE: 'SET_DURATION_DISTANCE',
  SET_BUS_LOCATION: 'SET_BUS_LOCATION',
  CLEAR_MAP: 'CLEAR_MAP',
};
